main: com.stardevllc.stargenerators.StarGeneratorsPlugin
version: ${version}
api-version: 1.13
name: ${name}
author: Firestar311
depend: [NBTAPI, StarCore]
commands: 
  itemgenerator:
    aliases: [ig]